add_executable(runtime_paths_test unit/RuntimePathsTest.cpp)
target_link_libraries(runtime_paths_test PRIVATE qvw_controllers Qt6::Test)
add_test(NAME runtime_paths COMMAND runtime_paths_test)
add_executable(log_rotation_test unit/LogRotationTest.cpp)
target_link_libraries(log_rotation_test PRIVATE qvw_infra Qt6::Test)
add_test(NAME log_rotation COMMAND log_rotation_test)
add_executable(export_cache_test unit/ExportCacheTest.cpp)
target_link_libraries(export_cache_test PRIVATE qvw_controllers Qt6::Test)
add_test(NAME export_cache COMMAND export_cache_test)
