#include "infrastructure/LogWriter.h"
#include <QtTest>
#include <QTemporaryDir>
#include <QFile>
#include <QJsonArray>
#include <QLockFile>
#include <QProcess>
#include <QThread>
#include <cstdlib>
using qvw::infra::LogWriter;
namespace {
QByteArray read(const QString &path){QFile f(path);if(!f.open(QIODevice::ReadOnly))return {};return f.readAll();}
bool fill(const QString &path,const QByteArray &data){QFile f(path);return f.open(QIODevice::WriteOnly)&&f.write(data)==data.size();}
}
class LogRotationTest:public QObject {
 Q_OBJECT
private slots:
 void crossProcessRotationWindowDoesNotDisableWriter(){QTemporaryDir tmp;const auto path=tmp.filePath("log.jsonl");LogWriter log(path);log.info("before");QProcess other;other.start(QCoreApplication::applicationFilePath(),{"--hold-lock",path,"missing"});QVERIFY(other.waitForReadyRead(3000));QVERIFY(other.readAllStandardOutput().contains("LOCKED"));QVERIFY(!QFileInfo::exists(path));log.info("contended");QVERIFY(log.isReady());QVERIFY(!log.lastError().isEmpty());QVERIFY(!QFileInfo::exists(path));QVERIFY(other.waitForFinished(3000));QCOMPARE(other.exitCode(),0);log.info("recovered");QVERIFY(log.isReady());QVERIFY(log.lastError().isEmpty());QVERIFY(read(path).contains("recovered"));}
 void recoversAfterWriterCrashesFollowingRename(){QTemporaryDir tmp;const auto path=tmp.filePath("log.jsonl");LogWriter log(path);log.info("before crash");QProcess other;other.start(QCoreApplication::applicationFilePath(),{"--crash-after-rename",path});QVERIFY(other.waitForFinished(3000));QCOMPARE(other.exitCode(),0);QVERIFY(!QFileInfo::exists(path));log.info("after crash");QVERIFY(log.isReady());QVERIFY(log.lastError().isEmpty());QVERIFY(read(path).contains("after crash"));QVERIFY(read(path+".1").contains("before crash"));}
 void constructorLockContentionCanRecover(){QTemporaryDir tmp;const auto path=tmp.filePath("log.jsonl");QProcess other;other.start(QCoreApplication::applicationFilePath(),{"--hold-lock",path,"empty"});QVERIFY(other.waitForReadyRead(3000));QVERIFY(other.readAllStandardOutput().contains("LOCKED"));LogWriter log(path);QVERIFY(log.isReady());QVERIFY(!log.lastError().isEmpty());QVERIFY(!QFileInfo::exists(path));QVERIFY(other.waitForFinished(3000));log.info("created after lock release");QVERIFY(log.isReady());QVERIFY(log.lastError().isEmpty());QVERIFY(read(path).contains("created after lock release"));}
 void concurrentProcessesRotateAndAppendValidRecords(){QTemporaryDir tmp;const auto path=tmp.filePath("log.jsonl");QVERIFY(fill(path,QByteArray(5*1024*1024-1,' ')+'\n'));QProcess a,b,c;int id=0;for(auto *process:{&a,&b,&c})process->start(QCoreApplication::applicationFilePath(),{"--write-many",path,QString::number(++id),"100"});for(auto *process:{&a,&b,&c}){QVERIFY(process->waitForFinished(5000));QCOMPARE(process->exitCode(),0);}QSet<QString> records;for(const auto &name:{path,path+".1",path+".2"})for(const auto &line:read(name).split('\n')){if(line.trimmed().isEmpty())continue;QVERIFY(line.size()<=64*1024);const auto doc=QJsonDocument::fromJson(line);QVERIFY(doc.isObject());records.insert(doc.object()["message"].toString());}QCOMPARE(records.size(),300);QVERIFY(QFileInfo(path).size()<=5*1024*1024);QVERIFY(!QFileInfo::exists(path+".3"));}
 void messagesAreBounded(){QTemporaryDir tmp;const auto path=tmp.filePath("log.jsonl");LogWriter log(path);log.info(QString(200000,QChar(0)));const auto line=read(path);QVERIFY(line.size()<=64*1024);QVERIFY(QJsonDocument::fromJson(line).isObject());}
 void argumentsAreBoundedAndRemainAnArray(){QTemporaryDir tmp;const auto path=tmp.filePath("log.jsonl");LogWriter log(path);QStringList args;for(int i=0;i<200;++i)args<<QString(20000,QChar(0));log.command(QString(20000,'p'),args,23);const auto line=read(path);QVERIFY(line.size()<=64*1024);const auto object=QJsonDocument::fromJson(line).object();QVERIFY(object["arguments"].isArray());QCOMPARE(object["exitCode"].toInt(),23);}
 void rotatesFiveMiBWithTwoBackups(){QTemporaryDir tmp;const auto path=tmp.filePath("log.jsonl");QVERIFY(fill(path,QByteArray(5*1024*1024,'a')));QVERIFY(fill(path+".1","previous"));QVERIFY(fill(path+".2","oldest"));LogWriter log(path);log.info("new event");QVERIFY(log.isReady());QCOMPARE(QFileInfo(path+".1").size(),qint64(5*1024*1024));QCOMPARE(read(path+".2"),QByteArray("previous"));QVERIFY(read(path).contains("new event"));QVERIFY(QFileInfo(path).size()<64*1024);QVERIFY(!QFileInfo::exists(path+".3"));}
 void rotationFailureIsVisible(){QTemporaryDir tmp;const auto path=tmp.filePath("log.jsonl");QVERIFY(fill(path,QByteArray(5*1024*1024,'a')));QDir().mkdir(path+".2");LogWriter log(path);log.info("cannot rotate");QVERIFY(!log.isReady());QVERIFY(!log.lastError().isEmpty());QCOMPARE(QFileInfo(path).size(),qint64(5*1024*1024));}
};
int main(int argc,char **argv){QCoreApplication app(argc,argv);const auto args=app.arguments();if(args.size()>=3&&(args[1]=="--hold-lock"||args[1]=="--crash-after-rename")){const auto path=args[2];QLockFile lock(path+".lock");if(!lock.tryLock(100))return 3;if(args[1]=="--crash-after-rename"||args.value(3)=="missing"){if(!QFile::rename(path,path+".1"))return 4;}if(args[1]=="--crash-after-rename")std::_Exit(0);QFile output;if(!output.open(stdout,QIODevice::WriteOnly))return 5;if(output.write("LOCKED\n")<0||!output.flush())return 6;QThread::msleep(900);if(args.value(3)=="missing"){QFile restored(path);if(!restored.open(QIODevice::Append))return 7;}return 0;}if(args.size()>=5&&args[1]=="--write-many"){LogWriter log(args[2]);for(int i=0;i<args[4].toInt();++i){bool saved=false;for(int attempt=0;attempt<30;++attempt){log.info(QStringLiteral("worker:%1:%2").arg(args[3]).arg(i));if(!log.isReady())return 8;if(log.lastError().isEmpty()){saved=true;break;}QThread::msleep(10);}if(!saved)return 9;QThread::msleep(1);}return 0;}LogRotationTest test;return QTest::qExec(&test,argc,argv);}
#include "LogRotationTest.moc"
