#include "services/VideoAssetImporter.h"
#include "services/ProjectStore.h"
#include "controllers/DocumentController.h"
#include <QtTest>
#include <QSignalSpy>
#include <QTemporaryDir>
#include <QFile>
#include <QJsonDocument>
#include <QJsonArray>
#include <QCryptographicHash>
using namespace qvw;
namespace {
// Unit fixtures deliberately replace ffprobe/ffmpeg. Real media integration is separate.
bool write(const QString &path,const QByteArray &bytes){QFile file(path);return file.open(QIODevice::WriteOnly)&&file.write(bytes)==bytes.size();}
QByteArray read(const QString &path){QFile file(path);return file.open(QIODevice::ReadOnly)?file.readAll():QByteArray();}
QString script(const QString &path,const QString &body){if(!write(path,("#!/usr/bin/python3\n"+body+"\n").toUtf8()))return {};QFile::setPermissions(path,QFile::ReadOwner|QFile::WriteOwner|QFile::ExeOwner);return path;}
QJsonObject metadata(QString codec="h264",QString fps="30/1",QString duration="8.0",QString frames="240",int width=720){return {{"streams",QJsonArray{QJsonObject{{"codec_type","video"},{"codec_name",codec},{"width",width},{"height",1280},{"avg_frame_rate",fps},{"r_frame_rate",fps},{"duration",duration},{"nb_read_frames",frames}}}},{"format",QJsonObject{{"format_name","mov,mp4,m4a,3gp,3g2,mj2"},{"duration",duration},{"tags",QJsonObject{{"major_brand","isom"}}}}}};}
QJsonObject timestamps(){QJsonArray frames;for(int i=0;i<240;++i)frames.append(QJsonObject{{"best_effort_timestamp_time",QString::number(i/30.0,'f',6)}});return {{"frames",frames}};}
QString jsonLiteral(const QJsonObject &value){return QString::fromUtf8(QJsonDocument(value).toJson(QJsonDocument::Compact)).replace('\\',"\\\\").replace('\'',"\\'").prepend('\'').append('\'');}
QString probe(const QString &path,const QJsonObject &value=metadata(),const QJsonObject &frames=timestamps()){return script(path,"import json,sys\nif '-count_frames' in sys.argv:\n print("+jsonLiteral(value)+")\nelse:\n assert '-show_frames' in sys.argv and '%+#240' in sys.argv and 'v:0' in sys.argv\n assert sys.argv.index('-show_frames')<sys.argv.index('-show_entries')\n print("+jsonLiteral(frames)+")");}

domain::Project project(QTemporaryDir &dir){domain::Project value;QString error;if(!services::ProjectStore::create(QStringLiteral(QVW_SOURCE_DIR "/templates/title-card"),dir.filePath("project"),"video",&value,&error))qFatal("%s",qPrintable(error));return value;}
QString movie(QTemporaryDir &dir){const auto path=dir.filePath("input.mp4");if(!write(path,"immutable fake video bytes"))return {};return path;}
}
class VideoAssetImporterTest:public QObject {
 Q_OBJECT
private slots:
 void importsOnlyAfterMetadataTimestampsAndDecodeCommit(){
    QTemporaryDir dir;auto original=project(dir);const auto path=movie(dir);const auto bytes=read(path);services::VideoAssetImporter importer;
    QSignalSpy imported(&importer,&services::VideoAssetImporter::imported),failed(&importer,&services::VideoAssetImporter::failed),commands(&importer,&services::VideoAssetImporter::commandFinished);
    auto decoder=script(dir.filePath("decode"),"import sys,pathlib\nassert '-xerror' in sys.argv and 'null' in sys.argv\nassert pathlib.Path(sys.argv[sys.argv.index('-i')+1]).read_bytes()==b'immutable fake video bytes'");
    QVERIFY(importer.start(original,path,probe(dir.filePath("probe")),decoder));QVERIFY(importer.active());QCOMPARE(original.assets.size(),0);
    QTRY_COMPARE_WITH_TIMEOUT(imported.size(),1,2000);QCOMPARE(failed.size(),0);QCOMPARE(commands.size(),3);QVERIFY(!importer.active());
    const auto result=qvariant_cast<domain::Project>(imported[0][0]);const auto asset=qvariant_cast<domain::Asset>(imported[0][1]);
    QCOMPARE(asset.mime,QString("video/mp4"));QCOMPARE(asset.hash,QString::fromLatin1(QCryptographicHash::hash(bytes,QCryptographicHash::Sha256).toHex()));QCOMPARE(asset.path,QString("assets/%1.mp4").arg(asset.hash));QCOMPARE(read(QDir(result.rootPath).filePath(asset.path)),bytes);
    domain::Project reopened;QString error;QVERIFY2(services::ProjectStore::load(result.manifestPath(),&reopened,&error),qPrintable(error));QCOMPARE(reopened.assets.size(),1);QCOMPARE(original.assets.size(),0);
 }
 void invalidMetadata_data(){QTest::addColumn<QJsonObject>("value");QTest::newRow("codec")<<metadata("hevc");QTest::newRow("fps25")<<metadata("h264","25/1");QTest::newRow("fps2997")<<metadata("h264","30000/1001");QTest::newRow("short")<<metadata("h264","30/1","7.9");QTest::newRow("few-frames")<<metadata("h264","30/1","8","239");QTest::newRow("unknown-framecount")<<metadata("h264","30/1","8","N/A");QTest::newRow("too-many-pixels")<<metadata("h264","30/1","8","240",40000);auto mov=metadata();auto format=mov["format"].toObject();format["tags"]=QJsonObject{{"major_brand","qt  "}};mov["format"]=format;QTest::newRow("mov")<<mov;}
 void invalidMetadata(){QFETCH(QJsonObject,value);QTemporaryDir dir;auto original=project(dir);const auto before=read(original.manifestPath());services::VideoAssetImporter importer;QSignalSpy failed(&importer,&services::VideoAssetImporter::failed),imported(&importer,&services::VideoAssetImporter::imported),commands(&importer,&services::VideoAssetImporter::commandFinished);
    QVERIFY(importer.start(original,movie(dir),probe(dir.filePath("probe"),value),script(dir.filePath("decode"),"raise Exception('decoder must not run')")));QTRY_COMPARE_WITH_TIMEOUT(failed.size(),1,2000);QCOMPARE(imported.size(),0);QCOMPARE(commands.size(),1);QCOMPARE(read(original.manifestPath()),before);QCOMPARE(QDir(original.rootPath).entryList({".qvw-video-*"},QDir::Dirs|QDir::Hidden).size(),0);}
 void invalidTimestamps_data(){QTest::addColumn<QJsonObject>("value");auto frames=timestamps()["frames"].toArray();auto jitter=frames;jitter[120]=QJsonObject{{"best_effort_timestamp_time","4.006667"}};QTest::newRow("jitter-despite-30fps-metadata")<<QJsonObject{{"frames",jitter}};auto duplicate=frames;duplicate[120]=frames[119];QTest::newRow("duplicate-time")<<QJsonObject{{"frames",duplicate}};auto missing=frames;missing[120]=QJsonObject{};QTest::newRow("missing-time")<<QJsonObject{{"frames",missing}};auto nonfinite=frames;nonfinite[120]=QJsonObject{{"best_effort_timestamp_time","NaN"}};QTest::newRow("nonfinite-time")<<QJsonObject{{"frames",nonfinite}};auto shortFrames=frames;shortFrames.removeLast();QTest::newRow("missing-frame")<<QJsonObject{{"frames",shortFrames}};auto extraFrames=frames;extraFrames.append(QJsonObject{{"best_effort_timestamp_time","8.000000"}});QTest::newRow("extra-frame")<<QJsonObject{{"frames",extraFrames}};auto delayed=frames;for(int i=0;i<240;++i)delayed[i]=QJsonObject{{"best_effort_timestamp_time",QString::number(0.5+i/30.0,'f',6)}};QTest::newRow("nonzero-origin")<<QJsonObject{{"frames",delayed}};auto drift=frames;for(int i=0;i<240;++i)drift[i]=QJsonObject{{"best_effort_timestamp_time",QString::number(i/30.0+i*0.000005,'f',6)}};QTest::newRow("timestamp-drift")<<QJsonObject{{"frames",drift}};}
 void invalidTimestamps(){QFETCH(QJsonObject,value);QTemporaryDir dir;auto original=project(dir);const auto before=read(original.manifestPath());services::VideoAssetImporter importer;QSignalSpy failed(&importer,&services::VideoAssetImporter::failed),imported(&importer,&services::VideoAssetImporter::imported),commands(&importer,&services::VideoAssetImporter::commandFinished);QVERIFY(importer.start(original,movie(dir),probe(dir.filePath("probe"),metadata(),value),script(dir.filePath("decode"),"pass")));QTRY_COMPARE_WITH_TIMEOUT(failed.size()+imported.size(),1,2000);QCOMPARE(failed.size(),1);QCOMPARE(imported.size(),0);QCOMPARE(commands.size(),2);QCOMPARE(read(original.manifestPath()),before);}
 void timestampProbeOutputIsBounded(){QTemporaryDir dir;auto original=project(dir);const auto before=read(original.manifestPath());const auto p=script(dir.filePath("probe"),"import sys\nif '-count_frames' in sys.argv:\n print("+jsonLiteral(metadata())+")\nelse:\n print('x'*70000)");services::VideoAssetImporter importer;QSignalSpy failed(&importer,&services::VideoAssetImporter::failed),imported(&importer,&services::VideoAssetImporter::imported);QVERIFY(importer.start(original,movie(dir),p,script(dir.filePath("decode"),"pass")));QTRY_COMPARE_WITH_TIMEOUT(failed.size()+imported.size(),1,2000);QCOMPARE(failed.size(),1);QVERIFY(failed[0][0].toString().contains("64 KiB"));QCOMPARE(read(original.manifestPath()),before);}
 void cancelTimestampProbeNeverRegisters(){QTemporaryDir dir;auto original=project(dir);const auto before=read(original.manifestPath()),marker=dir.filePath("frame-probe-started").toUtf8();const auto p=script(dir.filePath("probe"),"import sys,pathlib,time\nif '-count_frames' in sys.argv:\n print("+jsonLiteral(metadata())+")\nelse:\n pathlib.Path('"+QString::fromUtf8(marker)+"').write_text('started')\n time.sleep(5)");services::VideoAssetImporter importer;QSignalSpy imported(&importer,&services::VideoAssetImporter::imported),failed(&importer,&services::VideoAssetImporter::failed),commands(&importer,&services::VideoAssetImporter::commandFinished);QVERIFY(importer.start(original,movie(dir),p,script(dir.filePath("decode"),"pass")));QTRY_VERIFY_WITH_TIMEOUT(QFileInfo::exists(QString::fromUtf8(marker)),2000);QVERIFY(importer.active());importer.cancel();QVERIFY(!importer.active());QTest::qWait(50);QCOMPARE(imported.size(),0);QCOMPARE(failed.size(),0);QCOMPARE(commands.size(),2);QCOMPARE(commands.last()[2].toInt(),-1);QCOMPARE(read(original.manifestPath()),before);}
 void sourceMutationCannotChangeAcceptedBytes(){QTemporaryDir dir;auto original=project(dir);const auto path=movie(dir);const auto expected=read(path);services::VideoAssetImporter importer;QSignalSpy imported(&importer,&services::VideoAssetImporter::imported);QObject::connect(&importer,&services::VideoAssetImporter::commandFinished,&importer,[&](const QString &,const QStringList &args,int){if(args.contains("-count_frames")){QVERIFY(args.last()!=path);QVERIFY(write(path,"replacement source"));}});
    QVERIFY(importer.start(original,path,probe(dir.filePath("probe")),script(dir.filePath("decode"),"import pathlib,sys\nassert pathlib.Path(sys.argv[sys.argv.index('-i')+1]).read_bytes()==b'immutable fake video bytes'")));QTRY_COMPARE_WITH_TIMEOUT(imported.size(),1,2000);const auto result=qvariant_cast<domain::Project>(imported[0][0]);QCOMPARE(read(QDir(result.rootPath).filePath(result.assets.front().path)),expected);}
 void decodeFailurePreservesProject(){QTemporaryDir dir;auto original=project(dir);const auto before=read(original.manifestPath());services::VideoAssetImporter importer;QSignalSpy failed(&importer,&services::VideoAssetImporter::failed),imported(&importer,&services::VideoAssetImporter::imported);
    QVERIFY(importer.start(original,movie(dir),probe(dir.filePath("probe")),script(dir.filePath("decode"),"import sys\nprint('corrupt frame',file=sys.stderr)\nsys.exit(1)")));QTRY_COMPARE_WITH_TIMEOUT(failed.size(),1,2000);QCOMPARE(imported.size(),0);QCOMPARE(read(original.manifestPath()),before);}
 void cancelDecodeNeverRegisters(){QTemporaryDir dir;auto original=project(dir);const auto before=read(original.manifestPath());services::VideoAssetImporter importer;QSignalSpy commands(&importer,&services::VideoAssetImporter::commandFinished),imported(&importer,&services::VideoAssetImporter::imported);QVERIFY(importer.start(original,movie(dir),probe(dir.filePath("probe")),script(dir.filePath("decode"),"import time\ntime.sleep(5)")));QTRY_COMPARE_WITH_TIMEOUT(commands.size(),2,2000);importer.cancel();QVERIFY(!importer.active());QTest::qWait(100);QCOMPARE(imported.size(),0);QCOMPARE(read(original.manifestPath()),before);}
 void cancelDuringCopyCleansStaging(){QTemporaryDir dir;auto original=project(dir);services::VideoAssetImporter importer;QSignalSpy imported(&importer,&services::VideoAssetImporter::imported);QVERIFY(importer.start(original,movie(dir),probe(dir.filePath("probe")),script(dir.filePath("decode"),"pass")));importer.cancel();QTest::qWait(50);QCOMPARE(imported.size(),0);QCOMPARE(QDir(original.rootPath).entryList({".qvw-video-*"},QDir::Dirs|QDir::Hidden).size(),0);}
 void manifestFailureRollsBackOnlyOwnedCopy(){QTemporaryDir dir;auto original=project(dir);const auto path=movie(dir);services::VideoAssetImporter importer;QSignalSpy failed(&importer,&services::VideoAssetImporter::failed),imported(&importer,&services::VideoAssetImporter::imported);QObject::connect(&importer,&services::VideoAssetImporter::commandFinished,&importer,[&](const QString &,const QStringList &args,int){if(args.contains("-count_frames"))QVERIFY(write(original.manifestPath(),"unknown manifest"));});QVERIFY(importer.start(original,path,probe(dir.filePath("probe")),script(dir.filePath("decode"),"pass")));QTRY_COMPARE_WITH_TIMEOUT(failed.size(),1,2000);QCOMPARE(imported.size(),0);QCOMPARE(QDir(QDir(original.rootPath).filePath("assets")).entryList({"*.mp4"},QDir::Files).size(),0);QCOMPARE(read(original.manifestPath()),QByteArray("unknown manifest"));}
 void duplicatesValidateBytesAndMetadata(){QTemporaryDir dir;auto original=project(dir);const auto path=movie(dir);services::VideoAssetImporter importer;QSignalSpy imported(&importer,&services::VideoAssetImporter::imported),failed(&importer,&services::VideoAssetImporter::failed);const auto p=probe(dir.filePath("probe")),d=script(dir.filePath("decode"),"pass");QVERIFY(importer.start(original,path,p,d));QTRY_COMPARE_WITH_TIMEOUT(imported.size(),1,2000);auto result=qvariant_cast<domain::Project>(imported[0][0]);QVERIFY(importer.start(result,path,p,d));QTRY_COMPARE_WITH_TIMEOUT(imported.size(),2,2000);QCOMPARE(qvariant_cast<domain::Project>(imported[1][0]).assets.size(),1);QVERIFY(QFile::setPermissions(QDir(result.rootPath).filePath(result.assets[0].path),QFile::ReadOwner|QFile::WriteOwner));QVERIFY(write(QDir(result.rootPath).filePath(result.assets[0].path),"tampered"));QVERIFY(importer.start(result,path,p,d));QTRY_COMPARE_WITH_TIMEOUT(failed.size(),1,2000);QCOMPARE(imported.size(),2);QCOMPARE(read(QDir(result.rootPath).filePath(result.assets[0].path)),QByteArray("tampered"));}
 void preexistingCopySurvivesManifestFailure(){QTemporaryDir dir;auto original=project(dir);const auto path=movie(dir),hash=QString::fromLatin1(QCryptographicHash::hash(read(path),QCryptographicHash::Sha256).toHex());const auto target=QDir(original.rootPath).filePath("assets/"+hash+".mp4");QVERIFY(write(target,read(path)));services::VideoAssetImporter importer;QSignalSpy failed(&importer,&services::VideoAssetImporter::failed);QObject::connect(&importer,&services::VideoAssetImporter::commandFinished,&importer,[&](const QString &,const QStringList &args,int){if(args.contains("-count_frames"))QVERIFY(write(original.manifestPath(),"unknown manifest"));});QVERIFY(importer.start(original,path,probe(dir.filePath("probe")),script(dir.filePath("decode"),"pass")));QTRY_COMPARE_WITH_TIMEOUT(failed.size(),1,2000);QCOMPARE(read(target),read(path));}
 void unsafeAssetsDirectoryIsRejected(){QTemporaryDir dir,outside;auto original=project(dir);const auto assets=QDir(original.rootPath).filePath("assets");QVERIFY(QDir().rename(assets,assets+"-original"));QVERIFY(QFile::link(outside.path(),assets));services::VideoAssetImporter importer;QSignalSpy failed(&importer,&services::VideoAssetImporter::failed),commands(&importer,&services::VideoAssetImporter::commandFinished);QVERIFY(!importer.start(original,movie(dir),probe(dir.filePath("probe")),script(dir.filePath("decode"),"pass")));QCOMPARE(failed.size(),1);QCOMPARE(commands.size(),0);QCOMPARE(QDir(outside.path()).entryList(QDir::Files).size(),0);}
 void excessiveDecodeOutputNeverCommits(){QTemporaryDir dir;auto original=project(dir);const auto before=read(original.manifestPath());services::VideoAssetImporter importer;QSignalSpy failed(&importer,&services::VideoAssetImporter::failed),imported(&importer,&services::VideoAssetImporter::imported);QVERIFY(importer.start(original,movie(dir),probe(dir.filePath("probe")),script(dir.filePath("decode"),"import sys\nprint('x'*70000,file=sys.stderr)")));QTRY_COMPARE_WITH_TIMEOUT(failed.size(),1,2000);QCOMPARE(imported.size(),0);QCOMPARE(read(original.manifestPath()),before);}
 void projectLimitsAreEnforcedBeforeToolStart(){QTemporaryDir dir;auto original=project(dir);original.maxAssetBytes=3;services::VideoAssetImporter importer;QSignalSpy failed(&importer,&services::VideoAssetImporter::failed),commands(&importer,&services::VideoAssetImporter::commandFinished);importer.start(original,movie(dir),probe(dir.filePath("probe")),script(dir.filePath("decode"),"pass"));QTRY_COMPARE_WITH_TIMEOUT(failed.size(),1,2000);QCOMPARE(commands.size(),0);}
 void documentCancelsAndBlocksMutations(){QTemporaryDir dir;controllers::DocumentController controller;QVERIFY(controller.create(QStringLiteral(QVW_SOURCE_DIR "/templates/title-card"),dir.filePath("project"),"document"));controller.setMediaTools(probe(dir.filePath("probe")),script(dir.filePath("decode"),"import time\ntime.sleep(5)"),QProcessEnvironment::systemEnvironment());QSignalSpy assets(&controller,&controllers::DocumentController::assetImported),failures(&controller,&controllers::DocumentController::failed);QVERIFY(controller.importVideo(movie(dir)));QVERIFY(controller.importingVideo());QVERIFY(!controller.save());QVERIFY(!controller.importImage("missing"));QCOMPARE(failures.size(),2);controller.close();QVERIFY(!controller.importingVideo());QVERIFY(!controller.hasProject());QTest::qWait(100);QCOMPARE(assets.size(),0);}
};
QTEST_GUILESS_MAIN(VideoAssetImporterTest)
#include "VideoAssetImporterTest.moc"
